### ISSUE TITLE
Error: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by AlexMagicPro** [renowator/CryptosFaucets_Bot#13]
ideas of what it could be?

run from windows 10 build 18363

 🦾 ----------------- BOT STARTING ----------------- 🦾
Use email: ***********************

  🍀 Good Luck!

`(node:20352) UnhandledPromiseRejectionWarning: Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (C:\Users\***********\Desktop\CryptosFaucets_Bot-master\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:79:23)
    at async C:\Users\************\Desktop\CryptosFaucets_Bot-master\console_bot.js:125:23
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by renowator** [comment]
looks like you did not install Chromium browser

**Comment by AlexMagicPro** [comment]
No, the problem was that the sandbox was excluded:
`const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});`
