### ISSUE TITLE
Multiple at the same time

### ISSUE THREAD

**Issue by Mandarinos** [renowator/CryptosFaucets_Bot#15]
Hi there.

I wanted to run multiple instances of the bot at the same time in different terminal windows, but it seems this messes with the countdown a bit. It seems like the share the same file in which the "countdown" is stored. 
So I was just wondering, is it possible to run multiple instances of the bot at the same time?

**Comment by renowator** [comment]
The faucet website owners do not support such behavior. I do not recommend doing so as I doubt you will be able to withdraw your winnings like that. If you run a single instance from single ip you will get your withdrawals without problems (just contact them on Twitter).

For your question, you would just use multiple login/password details (one way or another) and then add an outside  for loop in the code to go through each login info. Do not recommend.
