### ISSUE TITLE
BNB & XEM Memo in .env?

### ISSUE THREAD

**Issue by yanrs17** [renowator/CryptosFaucets_Bot#25]
BNB and XEM require memo for withdrawal. Where do I input this information in .env? Thanks!
If it is impossible at the moment, is there a way to not withdraw automatically?

**Comment by renowator** [comment]
Not sure why you want to do this. For withdrawal to get processed you need to contact @cryptosfaucets on Twitter so they know you are real person and send you coins. Otherwise it will just not get processed. I recommend withdrawing manually

**Comment by yanrs17** [comment]
ok, then what are addresses used for?

**Comment by renowator** [comment]
The ones in sample.env - I am not sure, did not write that code
