### ISSUE TITLE
New issue  - No node found for selector: input[name=email]

### ISSUE THREAD

**Issue by umarm6** [renowator/CryptosFaucets_Bot#3]
![image](https://user-images.githubusercontent.com/12540495/100833494-15c37c80-3490-11eb-97b7-ef9656077393.png)

**Comment by renowator** [comment]
Hello @umarm6  the sites were under attack and Cloudflare DDoS protection system was enabled, this is why the bot is getting blocked. I am not sure if I can fix that, but hopefully the sites  get to function  as earlier again
